Added Constants.java and update classes for adding waitSeconds strategy
raunelgarcia/front-end-framework pull request #2
Opened 2024-03-14 14:25 UTC by raulgalera97

Also modify waitForVisibility, now you can pass seconds for waiting to the element.

2024-03-14 15:29 UTC, raunelgarcia commented on src/test/java/strategies/WaitStrategy.java
> +  public static void waitForVisibility(WebElement element, WebDriver driver, long time) {
este metodo lo dejamos con 8 0 12 por defecto como estaba, no hay que agregar otro parametro

2024-03-14 15:34 UTC, raunelgarcia requested changes

2024-03-14 15:34 UTC, raunelgarcia commented on src/test/java/pages/Marca.java
>      if (isVisible(ageButton)) {
este if esta de mas si ya hiciste un waitforVisibility, estas esperando doble

2024-03-14 15:34 UTC, raunelgarcia commented on src/test/java/pages/Marca.java
>  public class Marca {
las pages deben extender o heredar de una clase como base page que no se ha subido aun para no tener que instancias cada una de las clases como waitStrategy y otras

2024-03-14 15:34 UTC, raunelgarcia commented on src/test/java/pages/Marca.java
>      if (isVisible(ageButton)) {
falta el metodo isVisible que tenga como parametro de entrada web element y un tiempo de espera determinado

2024-03-14 16:01 UTC, raulgalera97 commented on src/test/java/pages/Marca.java
>      if (isVisible(ageButton)) {
No entiendo la necesidad de isVisible, si ya tenemos un método que es waitForVisibility sería redundante no?

2024-03-14 16:14 UTC, raunelgarcia commented on src/test/java/pages/Marca.java
>      if (isVisible(ageButton)) {
porque el waitforvisibility te petara cuando no haya un elemento pero el otro te dara un true o un false y no te petara la ejecucion, como por ejemplo un popout que esperes que salga y no sale. evita que no te falle la ejecucion por ese caso

2024-03-18 09:12 UTC, raulgalera97 commented on src/test/java/strategies/WaitStrategy.java
> +  public static void waitForVisibility(WebElement element, WebDriver driver, long time) {
vuelve a estar por defecto sin parametro usando Time.HIGH_TIMEOUT

2024-03-18 09:13 UTC, raulgalera97 commented on src/test/java/pages/Marca.java
>      if (isVisible(ageButton)) {
Ya esta cambiado

2024-03-18 09:14 UTC, raulgalera97 commented on src/test/java/pages/Marca.java
>  public class Marca {
quiero hacer este cambio cuando esta PR esté mergeada ya que es un cambio relativamente grande en la estructura del código

2024-03-18 09:14 UTC, raulgalera97 commented on src/test/java/pages/Marca.java
>      if (isVisible(ageButton)) {
método agregado en visibilityStrategy

2024-03-18 09:27 UTC, raunelgarcia commented on src/test/java/pages/Marca.java
> +    waitForVisibility(ageButton, driver);
podemos usar el click nuevo que incluye espera

2024-03-18 09:29 UTC, raunelgarcia commented on src/test/java/tests/CucumberRunner.java
> +          new String[]{
revisa el format code de google por favor

2024-03-18 09:48 UTC, raulgalera97 commented on src/test/java/pages/Marca.java
> +    waitForVisibility(ageButton, driver);
Listo!

2024-03-18 09:48 UTC, raulgalera97 commented on src/test/java/tests/CucumberRunner.java
> +          new String[]{
ya esta formateado :)

2024-03-18 10:05 UTC, raunelgarcia approved these changes

2024-03-18 10:07 UTC, raunelgarcia approved these changes

2024-03-18 10:07 UTC, merged